[package]
name = "integration_test"
version = "0.1.1"
edition = "2021"
description = "A simple demo for rust module system."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool = "1.0.3"
